---
- name: Populate service facts
  service_facts: {}

- name: Gather the package facts
  package_facts:
    manager: auto

- name: Has rke2 been installed already
  include_tasks: previous_install.yml

- include: images_tarball_install.yml
  when: not installed

- include: dist-hostfile.yml
  when: host_distribute|bool == true

- include: swapoff.yml

- name: "Check for binary tarball in {{ playbook_dir }}/tarball_install/rke2.linux-amd64.tar.gz"
  stat:
    path: "{{ playbook_dir }}/tarball_install/rke2.linux-amd64.tar.gz"
  register: rke2_binary_tarball_check
  delegate_to: 127.0.0.1
  become: false

- name: SLES/Ubuntu/Tarball Installation
  include: tarball_install.yml
  when:
    - |-
      ((ansible_facts['os_family'] != 'RedHat' and
      ansible_facts['os_family'] != 'Rocky') or
      rke2_binary_tarball_check.stat.exists == true)
      and not installed

- name: RHEL/CentOS Installation
  block:
    - name: Install redhat-lsb-core
      yum: name=redhat-lsb-core state=present
      when: "'redhat-lsb-core' not in ansible_facts.packages"
    - name: Reread ansible_lsb facts
      setup: filter=ansible_lsb*
      when: "'redhat-lsb-core' not in ansible_facts.packages"
    - include: rpm_install.yml
      when: not installed
  when:
    - ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'
    - rke2_binary_tarball_check.stat.exists == false

- name: Install Apparmor for Suse distros
  community.general.zypper:
    name: pattern:apparmor 
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'SUSE' or ansible_os_family == 'openSUSE Leap'
  
- name: Enable apparmor 
  ansible.builtin.systemd:
    name: apparmor
    state: started
    enabled: yes
  when:
    - ansible_os_family == 'SUSE' or ansible_os_family == 'openSUSE Leap'

# Set timezone (important for cluster components)
- name: Set timezone to Europe/Stockholm
  community.general.timezone:
    name: Europe/Stockholm

# Disable Firewalld
# We recommend disabling firewalld. For Kubernetes 1.19+, firewalld must be turned off.
- name: Disable FIREWALLD
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts.services["firewalld.service"] is defined

- include: network_manager_fix.yaml

- include: config.yml

- name: Add server iptables rules
  include_tasks: iptables_rules.yml
  when: add_iptables_rules|bool == true
#    - ansible_facts.services["iptables.service"] is defined
#    - add_iptables_rules is true

- include: add-audit-policy-config.yml
  when:
    - audit_policy_config_file_path | length > 0

- include: add-registry-config.yml
  when: registry_config_file_path | length > 0

- name: Run CIS-Hardening Tasks
  include_role:
    name: rke2_common
    tasks_from: cis-hardening

